[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "data_project"
authors = [
  { name="Mihaela Duta", email="mihaela.duta@dtc.ox.ac.uk" },
]
dynamic = ["version", "description"]
requires-python = ">=3.7"